name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      Authentication__Google__ClientId: ${{ secrets.Authentication__Google__ClientId }}
      Authentication__Google__ClientSecret: ${{ secrets.Authentication__Google__ClientSecret }}
      Authentication__Jwt__Key: ${{ secrets.Authentication__Jwt__Key }}
      Authentication__Jwt__Issuer: ${{ secrets.Authentication__Jwt__Issuer }}
      Authentication__Jwt__Audience: ${{ secrets.Authentication__Jwt__Audience }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the application
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

  docker-build-push:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/crazycows/backend_devops_rejsekort_v2:latest
